services:
  - type: web
    name: fixr-backend
    env: node
    region: oregon
    plan: free
    repo: https://github.com/mostafa-meerzad/Fixr-Platform
    branch: mobile-ui-v2
    root: .
    buildCommand: npm install --workspace=@fixr/backend --include-workspace-root && npm run build --workspace=@fixr/shared && npm run prisma:generate --workspace=@fixr/backend && npm run build --workspace=@fixr/backend
    startCommand: npm run start:prod --workspace=@fixr/backend
    envVars:
      - key: DATABASE_URL
      - key: JWT_ACCESS_SECRET
      - key: JWT_REFRESH_SECRET
      - key: JWT_ACCESS_EXPIRES_IN
      - key: JWT_REFRESH_EXPIRES_IN
      - key: ALLOWED_ORIGINS
      - key: WHATSAPP_API_URL
      - key: WHATSAPP_PHONE_NUMBER_ID
      - key: WHATSAPP_ACCESS_TOKEN
      - key: OTP_EXPIRY_MINUTES
      - key: DEV_OTP_CODE
      - key: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
      - key: FIREBASE_PROJECT_ID
      - key: FIREBASE_PRIVATE_KEY
      - key: FIREBASE_CLIENT_EMAIL
      - key: STREAM_API_KEY
      - key: STREAM_API_SECRET
      - key: ADMIN_EMAIL
      - key: ADMIN_PASSWORD
      - key: NODE_ENV
