export declare enum UserRole {
    HOMEOWNER = "HOMEOWNER",
    EXPERT = "EXPERT",
    ADMIN = "ADMIN"
}
export declare enum JobStatus {
    DRAFT = "DRAFT",
    OPEN = "OPEN",
    ASSIGNED = "ASSIGNED",
    EN_ROUTE = "EN_ROUTE",
    ARRIVED = "ARRIVED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETION_REQUESTED = "COMPLETION_REQUESTED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    DISPUTED = "DISPUTED"
}
export declare enum Urgency {
    EMERGENCY = "EMERGENCY",
    TODAY = "TODAY",
    SCHEDULED = "SCHEDULED"
}
export declare enum VerificationStatus {
    PENDING = "PENDING",
    VERIFIED = "VERIFIED",
    REJECTED = "REJECTED"
}
export declare enum DisputeReason {
    PRICE_DISPUTE = "PRICE_DISPUTE",
    WORK_QUALITY = "WORK_QUALITY",
    NO_SHOW = "NO_SHOW",
    COMMUNICATION_ISSUE = "COMMUNICATION_ISSUE",
    OTHER = "OTHER"
}
export declare enum CreditTransactionType {
    WELCOME_GRANT = "WELCOME_GRANT",
    PURCHASE = "PURCHASE",
    BID_SPEND = "BID_SPEND",
    BID_REFUND = "BID_REFUND",
    ADMIN_ADJUSTMENT = "ADMIN_ADJUSTMENT"
}
export declare enum NotificationType {
    JOB_POSTED = "JOB_POSTED",
    BID_RECEIVED = "BID_RECEIVED",
    BID_ACCEPTED = "BID_ACCEPTED",
    BID_WITHDRAWN = "BID_WITHDRAWN",
    NEW_MESSAGE = "NEW_MESSAGE",
    EXPERT_EN_ROUTE = "EXPERT_EN_ROUTE",
    EXPERT_ARRIVED = "EXPERT_ARRIVED",
    COMPLETION_REQUESTED = "COMPLETION_REQUESTED",
    JOB_COMPLETED = "JOB_COMPLETED",
    JOB_CANCELLED = "JOB_CANCELLED",
    REVIEW_REQUESTED = "REVIEW_REQUESTED",
    VERIFICATION_APPROVED = "VERIFICATION_APPROVED",
    VERIFICATION_REJECTED = "VERIFICATION_REJECTED"
}
export declare enum Language {
    FA = "fa",
    EN = "en"
}
